ALTER SESSION SET CURRENT_SCHEMA = APPUSER;

CREATE TABLE SAMPLEMODEL (
    ID      VARCHAR2(100) CONSTRAINT SAMPLEMODEL_PK PRIMARY KEY,
    COLUMN1 VARCHAR2(255),
    COLUMN2 VARCHAR2(255)
);
ALTER SESSION SET CURRENT_SCHEMA = HR;

CREATE TABLE SAMPLEMODEL ( ID VARCHAR2(100), COLUMN1 VARCHAR2(100), COLUMN2 VARCHAR2(100), CONSTRAINT SAMPLEMODEL_PK PRIMARY KEY (ID), CONSTRAINT SYS_C008529 CHECK ("ID" IS NOT NULL));
CREATE UNIQUE INDEX SAMPLEMODEL_PK ON SAMPLEMODEL (ID);
